### ISSUE TITLE
运行Demo时遇到几个问题

### ISSUE THREAD

**Issue by ALittleHibiscus** [alibaba/OCAnnotation#1]
你好，运行Demo的时候遇到几个问题
1.编译时提示`'OCAnnotationAnnotationConfig.gen.h' file not found`，好像是文件引用路径配置有点问题，配置的路径是`Example/OCAnnotation/OCAnnotationAnnotationConfig.gen.h`，而实际生成文件的路径是`Example/OCAnnotationAnnotationConfig.gen.h`；
2.在`OCAAppDelegate.m`或者`OCAViewController.m`中添加`#pragma annotation...`后build，`OCAnnotationAnnotationConfig.gen.h`中都未生成对应的AnnotationConfigs字典，但是在`Tests.m`中添加可以成功生成，好像是因为，脚本扫描文件时候，用的是File Group，而Demo中的Group `Example for OCAnnotation` 与文件目录 `OCAnnotation` 不匹配导致；
3.修改ruby代码，在Script目录执行`rake install`的时候，"The validation error was 'ocannotation-0.1.0 contains itself (ocannotation-0.1.0.gem), check your files list'."，是不是把build生成的gem放到pkg/目录就不会有这个问题，不知道说的有没有问题.

再说一下一点想法，简单看了下实现，好像整个实现是基于正则的文件扫描，是不是可以考虑基于语义（预处理，抽象语法树之类的）的实现，依赖字符串，感觉有时候就会遇到上述第2点那样没有考虑到的问题，另外，如果是基于clang-llvm之类的，Swift版本的实现是不是就会快一点。之前看到过一篇文章[Implementing a Custom Directive Handler in Clang](https://blog.quarkslab.com/implementing-a-custom-directive-handler-in-clang.html) 不知道是不是也可以来实现项目中的效果。

**Comment by JackLian** [comment]
你好，非常感谢反馈的这些问题！
1、2、3 三个问题我们尽快处理下~

目前这个项目确实基于正则的文本扫描做的，好处是与语言无关，也可以做快速迁移，关于后边的你说的基于抽象语法树的实现还是很有借鉴意义的，我们之前也考虑过，但这已经属于另外一个实现路线了，暂时不会在这个项目里来搞了。

**Comment by ALittleHibiscus** [comment]
多谢解答，还有一些想法也说一下，基于字符串正则匹配的方式有一个缺陷是丢失了语义，依赖代码书写结构比较强，比如有时候比较难判断它是属于方法声明还是注释，有些特殊的代码书写情况下，就连作用范围的判断可能都会出现问题. 这个项目是针对OC语言实现的，文本处理中依赖OC语法，而与Swift语法的差异性导致Swift版本的实现需要另外处理，很难公用同一套核心解析代码，再就是对于Swift，如果想利用收集到的信息，配合OC运行时，可能就需要约束Swift代码的书写方式，混编的时候可能还有其他问题. 基于语义的实现，也许也无法完全公用同一套实现(单针对OC/Swift，基于IR的处理也许有戏？)但是感觉相比文本处理，基于编译中间数据结构的处理，依托于语义上的保障，获取到的上下文信息感觉应该会更准确一些

上面提到的部分问题，是在测试Demo时不同写法下遇到的几个问题，这个配注一下，希望有点帮助

1.先在方法上添加
`#pragma annotation(type:"remoteLog",remoteLogId:"123")
- (void)applicationWillResignActive:(UIApplication *)application`
然后注释掉
`/*
#pragma annotation(type:"remoteLog",remoteLogId:"123")
 */
- (void)applicationWillResignActive:(UIApplication *)application`
或者
`/*
#pragma annotation(type:"remoteLog",remoteLogId:"123")
- (void)applicationWillResignActive:(UIApplication *)application
{
}
 */`
依旧会生成config信息，貌似用'//'没有问题，用'/**/'好像有点问题
类似的以下的也好像有点问题，好像顶格写会生成，向右缩进以下就不会
`/*
 添加annotation示例如下:
 
#pragma annotation(type:"default",remoteLogId:"123")
@interface MyClass : NSObject
@end

@implementation MyClass
@end
 */`

2.我使用的项目中用到了RN，会自定义的一些Module，然后export方法，类似下面这种情况，也有点问题
`#pragma annotation(type:"test",remoteLogId:"123")
RCT_EXPORT_METHOD(test)
{ 
}`

上述这些情况可能比较特殊，但是也暴露出仅依赖正则匹配扫描字符串，在完全还原代码语义上，可能会有些问题，如果要给出一个非常完备的实现，其实已经变成要实现一个类似于预处理tokenlize的过程，如果要大规模使用，是不是基于语义的实现会稍微好一些

最后，项目中获取method（class和property的还没想到使用场景）相关的metadata，然后进行AOP，应该是一个主要的使用场景，同样的，还想到了下面两种实现思路

1.基于约定的动态调用，实现逻辑注入，在原有添加annotation的方法体前面添加类似下面的代码，通过定义宏解决书写麻烦的问题
`- (void)someMethod
{
    NSString *suffix = @"AnnotationHandler";
    NSString *className = [NSString stringWithFormat:@"%@%@", NSStringFromClass(self.class), suffix];
    Class clz = NSClassFromString(className);
    SEL sel = @selector(handleAnnotationClass:userInfo:);
    if ([clz instancesRespondToSelector:sel]) {
        id handler = [[clz alloc] init];
        [handler performSelector:sel withObject:[self class] withObject:@{
                                                                          @"type": @"remoteLog",
                                                                          @"remoteLogId": @"xxx",
                                                                          }];
    }
    // ...
}`
好处是免去提前的统一注册处理，基于约定动态调用，由于是静态代码处理逻辑，不如method-swizzle的话可以控制是前置还是后置执行，不过有些场景下这也是一种解决问题的思路

2.基于clang attribute将元数据写入__DATA段
同1一样，在原有添加annotation的方法体前面添加类似BeeHive项目中通过宏来注册Module时用到的代码
`#define BeeHiveDATA(sectname) __attribute((used, section("__DATA,"#sectname" ")))`
可执行文件加载时通过`getsectiondata`获取数据进行处理

**Comment by JackLian** [comment]
1. demo工程有些误导，config.h文件是需要oca_build之后手动添加到工程，现已修复
2. 修复
3. 可以build前删掉已有gem或者更新version.h(版本号升级一下)
